apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: approlebinding
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
subjects:
  - kind: ServiceAccount
    name: operationsadmin
    namespace: dev

