apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
  labels:
    app: comfurniture
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: comfurniturepods
