apiVersion: v1
kind: Service
metadata:
  labels:
    app: comfurniture
spec:
  type: loadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: comfurniturepods
